---
abstract: 'A simple client for interacting with Confluent Schema Registry.'
author:
  - 'Alvaro Livraghi'
build_requires:
  ExtUtils::MakeMaker: '0'
  Math::BigInt: '1.89'
  Test::Exception: '0.43'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Confluent-SchemaRegistry
no_index:
  directory:
    - t
    - inc
requires:
  Aspect: '1.04'
  Avro::Schema: '0'
  JSON::XS: '3.02'
  REST::Client: '273'
  Try::Tiny: '0.22'
  perl: '5.010'
resources:
  bugtracker: https://github.com/alivraghi/Confluent-SchemaRegistry/issues
  homepage: https://github.com/alivraghi/Confluent-SchemaRegistry
  repository: https://github.com/alivraghi/Confluent-SchemaRegistry.git
version: '0.02'
