---
abstract: 'A simple client for interacting with Confluent Schema Registry.'
author:
  - 'Alvaro Livraghi'
build_requires:
  ExtUtils::MakeMaker: '0'
  Math::BigInt: '1.89'
  Test::Exception: '0.43'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Confluent-SchemaRegistry
no_index:
  directory:
    - t
    - inc
    - t
    - inc
requires:
  Aspect: v1.40.0
  Avro::Schema: v1.10.1
  HTTP::Status: v6.270.0
  JSON::XS: v4.30.0
  REST::Client: v273.0.0
  Try::Tiny: v0.300.0
  perl: '5.010'
resources:
  bugtracker: https://github.com/alivraghi/Confluent-SchemaRegistry/issues
  homepage: https://github.com/alivraghi/Confluent-SchemaRegistry
  repository: https://github.com/alivraghi/Confluent-SchemaRegistry.git
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
